apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-webapp
  name: react-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-webapp
    spec:
      containers:
      - image: gcr.io/synchrocise-dev/app:v1
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3001
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: react-webapp
  labels:
    run: react-webapp
spec:
  ports:
  - port: 3001
    protocol: TCP
  selector:
    app: react-webapp
  type: LoadBalancer