apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend
  namespace: default
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"